fixing up functions

diff --git a/zsh/zsh-functions b/zsh/zsh-functions
--- a/zsh/zsh-functions
+++ b/zsh/zsh-functions
@@ -22,7 +22,19 @@ nsla() {
 
 # get expiry date from server
 ced() {
-openssl s_client -servername $@ -connect $@:443 2>&1 < /dev/null | openssl x509 -noout -dates || exit
+test=$(nslookup $@)
+if [ $? -eq 0 ]; then
+    openssl s_client -servername $@ -connect $@:443 2>&1 < /dev/null | openssl x509 -noout -dates || exit
+    return 1
+else
+    echo 'host not found'
+    return 0
+fi
+}
+
+# get SANs from remote server
+gsan() {
+openssl s_client -connect $@:443 </dev/null 2>/dev/null | openssl x509 -noout -text | grep DNS:
 }
 
 #connect airpods and make default output/input
